### PR TITLE
Tutorial Update : Fogflow Edge Computing

### PR DESCRIPTION
**Pull request by pradumnnec**
Tutorial has been updated with latest support provided in fogflow with new components and as per latest code changes.

### CODE REVIEW

**Comment by jason-fox** [comment]
Is this NGSI-v2 or NGSI-LD? If it is the latter it should be merged to the LD branch instead.

Can you confirm if this is updates for working with v2? 
Or shall I switch the merge branch to LD?

**Comment by pradumnnec** [comment]
This tutorial is NGSI-v2 compliant, so you can merge this with NGSI-v2 branch only. For NGSI-LD,  I can make few changes and let you know later on. The current tutorial is related to NGSI-v2.

**Comment by jason-fox** [comment]
OK, I'll merge this to `NGSI-v2`, `master` **and** `NGSI-LD` for now.

the `NGSI-LD`  branch is just a placeholder for further changes. If you could raise a separate PR for the additional NGSI-LD changes against the `NGSI-LD` branch I can then publish the **NGSI-LD** FogFlow tutorial into the complete list of [NGSI-LD Tutorials](https://ngsi-ld-tutorials.readthedocs.io/)

Meanwhile I can amend the published [NGSI-v2 Tutorials](https://fiware-tutorials.readthedocs.io/) to include these changes.

**Comment by jason-fox** [comment]
@pradumnnec 

The tutorial states:

> 2.  Start both Edge IoT Broker and FogFlow Worker. If the edge node is ARM-based, then attach arm as the command
>    parameter.
>
> ```
>  ./start.sh
> ```


But `start.sh` still refers to the deleted `metricbeat.docker.yml` file - how should this be altered?

**Comment by pradumnnec** [comment]
Okay, It would work for time being and meanwhile, I will work towards NGSI-LD tutorial. I would alter start.sh with latest changes.

**Pull request merged**
